#!/bin/sh
#script auto installer SSH + VPN LT2P/IPSec PSK
#created bye HideSSH.com and Kumpulanremaja.com
#OS Debian 9
#belajar

#manejemen WG
wget -O install-wireguard "https://www.dropbox.com/s/p89ubjpypmk26rv/install-wireguard?dl=1" && chmod +x install-wireguard && ./install-wireguard

#instalasai SSH 
wget https://raw.githubusercontent.com/4hidessh/hidessh/main/ssh.sh && chmod +x ssh.sh && ./ssh.sh
