#!/bin/sh
#script auto installer SSH + SSLH
#created bye HideSSH.com and Kumpulanremaja.com
#OS Debian 9
apt-get update && apt-get upgrade -y
apt-get install wget curl -y



wget https://raw.githubusercontent.com/4hidessh/hidessh/main/l2tp/install && chmod +x install && bash install

#add remove account VPN lt2p
wget -O /usr/local/bin/stdev-l2tp-add-user "https://raw.githubusercontent.com/4hidessh/sshtunnel/master/stdev-l2tp-add-user"
wget -O /usr/local/bin/stdev-l2tp-remove-user "https://raw.githubusercontent.com/4hidessh/sshtunnel/master/stdev-l2tp-remove-user"

# shared key
wget -O /usr/local/bin/stdev-l2tp-get-psk "https://raw.githubusercontent.com/4hidessh/sshtunnel/master/stdev-l2tp-get-psk"

#edit password shared l2tp
wget -O /etc/ipsec.secrets "https://raw.githubusercontent.com/4hidessh/sshtunnel/master/ipsec.secrets"


#permition
chmod +x /usr/local/bin/stdev-l2tp-add-user
chmod +x /usr/local/bin/stdev-l2tp-remove-user
chmod +x /usr/local/bin/stdev-l2tp-get-psk

#auto installer SSH + Dropbear +Stunnel + SSLH Multi Port 
wget https://raw.githubusercontent.com/4hidessh/hidessh/main/ssh/lt2p.sh && chmod +x lt2p.sh && ./lt2p.sh
